### ISSUE TITLE
명명법 통합

### ISSUE THREAD

**Issue by F-hiller** [KNU-SYS3/SystemProgramming_TEAM3#11]
변수를 이름을 적는다면 다양한 방식으로 표기할 수 있습니다. user 구조체의 name데이터를 변수명으로 나타내려고 한다면
1. user_name
2. user_NAME
3. USER_NAME
4. userName
5. UserName
등이 있습니다. 이를 통일하면 좋을 것 같습니다. 
댓글로 의견주시면 감사하겠습니다. 화요일까지 받은 내용을 바탕으로 진행하도록 하겠습니다.

**Comment by F-hiller** [comment]
저는 1번 방식으로 진행하고 싶습니다.

**Comment by seoyeong10yun** [comment]
저는 1번 아니면 3번 방식이 나을 것 같습니다.

**Comment by 2insung** [comment]
하고 싶은대로 합시다.

**Comment by jijun0129** [comment]
1번과 4번을 섞어서 사용했습니다.
