### ISSUE TITLE
데이터베이스 // 처음 접속할 때 이전 채팅 몇 줄 정도 보여줄까요

### ISSUE THREAD

**Issue by 2insung** [KNU-SYS3/SystemProgramming_TEAM3#20]
제 생각에는 이전 채팅에서 20줄 정도 잘라서 보여주면 좋을 거 같네요

**Comment by F-hiller** [comment]
20줄이면 화면에 어느정도로 차나요? 반틈 정도 있으면 적당할 것 같습니다.

**Comment by 2insung** [comment]
처음 시작할 때 화면에 어느정도 차는 것 같습니다 
![image](https://user-images.githubusercontent.com/84179188/147257008-b4720f46-9a70-41a9-a4e3-736f97cb993c.png)

**Comment by jijun0129** [comment]
최대 20줄로 하는 것으로 합시다.
