### ISSUE TITLE
server / client 구분 폴더 없이 한 폴더에 넣었습니다.

### ISSUE THREAD

**Issue by 2insung** [KNU-SYS3/SystemProgramming_TEAM3#21]
이유는 원래 데이터베이스 파일이 server 폴더에 있었는데, 데이터베이스의 내용을 클라이언트에 출력을 해줘야하는데 폴더가 달라 출력이 불가능했습니다. 그리고 보니까 header 파일이 겹치는 것 같아 그냥 폴더 구분없이 하나의 폴더 안에 전부 있도록 해줬어요. Makefile도 변경했습니다. 괜찮겠죠?

**Comment by 2insung** [comment]
일단 안 지우고 exe 폴더만 추가했습니다.

**Comment by jijun0129** [comment]
exe 파일 ChattingProgram으로 바꾸어 밖에 있던 파일들 정리 하였습니다.
