### ISSUE TITLE
데이터베이스 관련 업데이트 내용입니다

### ISSUE THREAD

**Issue by 2insung** [KNU-SYS3/SystemProgramming_TEAM3#22]
폴더 한 개로 축소했습니다.
make 잘 되고, 2개 잘 만들어집니다

![image](https://user-images.githubusercontent.com/84179188/147258470-9c5e3a03-798f-49e9-906f-91188a1ddd75.png)

**Comment by 2insung** [comment]
![image](https://user-images.githubusercontent.com/84179188/147258805-da74778a-60ae-4975-a1b8-8e4a34785d8c.png)

**Comment by 2insung** [comment]
![image](https://user-images.githubusercontent.com/84179188/147259071-3b23349b-835a-4223-b852-c590975dc062.png)
이렇게 이전 채팅의 내용이 나옵니다.
근데 한 줄 더 출력되네요. 이건 고치도록 하겠습니다..

**Comment by 2insung** [comment]
고쳤습니다.
![image](https://user-images.githubusercontent.com/84179188/147260883-6569ef7f-728a-4cd2-b5a9-0d7f7cb53159.png)
![image](https://user-images.githubusercontent.com/84179188/147260937-d3da8040-a2e4-44d7-8827-14fd19abb9ff.png)

**Comment by jijun0129** [comment]
지금 실행했을 때 이름은 저장이 안되어있는 것 같은데 왜 그런건가요?

**Comment by 2insung** [comment]
이름 저장하도록 수정했습니다
