### ISSUE TITLE
Notion Page 추가

### ISSUE THREAD

**Issue by F-hiller** [KNU-SYS3/SystemProgramming_TEAM3#26]
조금 늦은 감이 없지않아 있지만 파트별로 어떤 일을 했는지 적을 수 있는 공간을 마련했습니다. 들어가셔서 작성하시면 됩니다. 
https://www.notion.so/sys3/a1e0dd14ace44728a1575f39beb92d85

**Comment by jijun0129** [comment]
들어가서 자기 파트를 자기가 적는 것으로 합시다. 
제가 socket부분 작성하겠습니다.

**Comment by seoyeong10yun** [comment]
client는 다 완성되어서 완료 부분만 채우면 될 것 같습니다.
