### ISSUE TITLE
헤더 수정 및 함수 추가. client와 socket part 수정해야할 부분이 있는 것 같습니다.

### ISSUE THREAD

**Issue by F-hiller** [KNU-SYS3/SystemProgramming_TEAM3#28]
중복되는 내용이랑 디버그 확인과 같이 불필요한 코드들을 삭제하고 header로 함수 선언들을 옮겼습니다. 또한 사용자 정보를 DB_User에 추가하는 기능들을 넣었습니다. 확인하시고 이상한 점이 있다면 알려주세요.
또한 제가 코드를 확인하다가 이름 설정하는 부분이 아직 제대로 구현이 안되있어서 기능을 만들어보려다가 socket으로 정보를 주고 받는 과정이 필요하여 고치지 못했습니다. client와 socket 쪽에서 어떤 식으로 이름을 사용해도 되는 지에 관한 정보를 주고 받을 지 정하셔서 구현해주시면 감사하겠습니다.

**Comment by jijun0129** [comment]
서버에 클라이언트가 정한 이름을 받으면 데이터베이스에 있는 이름과 비교한 후 정보를 클라이언트로 전달하는 것으로 하였습니다.
