### ISSUE TITLE
server파트 궁금한 점 있습니다.

### ISSUE THREAD

**Issue by F-hiller** [KNU-SYS3/SystemProgramming_TEAM3#29]
cli->address = connectSocket; 문장이 있는데 그 외에 사용되는 곳이 없습니다. address는 DB에 저장할 필요가 있나요?

**Comment by jijun0129** [comment]
따로 쓰이는 곳은 없는 것 같습니다.

**Comment by jijun0129** [comment]
삭제하고 진행하는 것으로 하겠습니다.
