### ISSUE TITLE
명령어 출력부분 질문입니다. 

### ISSUE THREAD

**Issue by jijun0129** [KNU-SYS3/SystemProgramming_TEAM3#30]
https://github.com/KNU-SYS3/SystemProgramming_TEAM3/blob/6bde29ee7845b5b1ea80673ee9f4adebdfeb872d/ChattingProgram/client.c#L110-L121

여기 부분에서 !message는 어떤 명령어인가요?

**Comment by F-hiller** [comment]
전채 채팅으로 대체되어서 사용하지 않는 명령어입니다.
