### ISSUE TITLE
UI 업데이트 내용

### ISSUE THREAD

**Issue by seoyeong10yun** [KNU-SYS3/SystemProgramming_TEAM3#39]
수정사항
1. stdscr에 비해 채팅 스크린이 작아서 stdscr의 테두리를 그리는 함수인 box(stdscr, 0, 0)을 삭제했습니다.
2. client_send_message()에서 입력한 문자열을 출력하는 것(wprintw)보다 server에서 보내는 문자열이 먼저 출력(write)되어 문자열이 출력되는 문제가 있었기 때문에 코드를 수정했습니다.

문제점
1. 여전히 한글 출력이 안 됩니다.
2. ncurses 라이브러리 내에서 스크린 크기를 조정하는 함수가 별도로 없기 때문에, 처음에 지정한 스크린(WINDOW* ~)보다 작은 화면에서 client.ext를 실행할 시 UI가 잘리는 문제가 있습니다.

**Comment by 2insung** [comment]
한글 출력이 되지 않아 안타깝습니다.
