### ISSUE TITLE
다른 컴퓨터의 접속문제

### ISSUE THREAD

**Issue by jijun0129** [KNU-SYS3/SystemProgramming_TEAM3#41]
다른 컴퓨터에서 하나의 채팅 프로그램에 접속하려고 할 때 실행을 해도 연결이 되지 않는 문제가 있습니다.

**Comment by 2insung** [comment]
저도 잘 안 되네요.

**Comment by seoyeong10yun** [comment]
같은 공유기를 사용하면 가능하던데 뭐가 문제일까요?

**Comment by jijun0129** [comment]
[https://luminitworld.tistory.com/45](url)
포트 포워딩 때문인 것 같습니다. 
코드에는 문제가 없고 공유기 설정 문제인 것 같으니 그냥 하는 것으로 합시다.
