### ISSUE TITLE
데이터베이스 관련 문제

### ISSUE THREAD

**Issue by 2insung** [KNU-SYS3/SystemProgramming_TEAM3#8]
함수하고 파일 추가해서 올렸는데 
유저의 이름, id , 채팅 정보에 관한 자료가
어차피 한 명의 유저에서 이루어지니까 구조체를 사용하여
변수를 저장해서 데이터베이스로 보내는 건 어떨까요?

**Comment by 2insung** [comment]
그리고 파일 관련해서는 fopen 함수를 사용하는 것이 어떨까요?

**Comment by jijun0129** [comment]
회의 시간에 이렇게 하는 것으로 정하였습니다.
